<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://api.biblesupersearch.com/api?request=John%203%3A16',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'Cookie: XSRF-TOKEN=eyJpdiI6IlJxbXZwbjVMcmIzaVlsdE14SlRjaEE9PSIsInZhbHVlIjoiaVZLN1B5NFYyRlh6OHdSTTRpalBKRFdRV3h3NklUNDBnQ2FQc3dRTGpadS9uUlpsc0Z6V1N5UWE1RG1wdjJCTXMxbkhmRUxFaUpPUUVLUXRMTWZtVTVnVURPMkEycFZJTDJLL09zUFBBRnVRN3ZWbCt1QkdqUHE1bUlLQytGWGMiLCJtYWMiOiI5ZjVkODc1ZDkzYzljYjc1ODg2MDEwYjZkNDI2ZTQ1MDcxOWE3ZDlmNDhiNDFjZGYxYmE3NTM2NmY3ODZhNWJmIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6IldTYW5YYThVdWxDcVpQamN6WTdDWWc9PSIsInZhbHVlIjoicVdCQWdxQkwrZkc1ODVLcEVWL2xtSXhWSFAwRjQyLzFHVUFYVTAvQkZ5ZzFqamk2VzVPbE9lNWkzb2FNL0drZkRrUFMzZ3lyL0R0cE9jaUcwQmNLemZEckFzZXJtS0wrNXBhai9tRUlGcTVtZHFRcGp1TDNBRlgxUDhkemhtS0MiLCJtYWMiOiJkNmIzN2I4YzdkMGEwMDdhMjkxYmY0MmViZmRiZjQ2NWI3ZjJmYjhlNTQ0ZTcxZDEyMDdkMDJlMjBmZWU0OWExIiwidGFnIjoiIn0%3D'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;