openapi: 3.1.0
info:
  version: 6.0.4
  title: Bible SuperSearch API Documentation
  contact:
    name: AIC Web Tech
    url: https://aicwebtech.com/
  license:
    name: GNU GPL v3.0
    url: null
externalDocs:
  description: To install the API on your website, click here.
  url: https://www.biblesupersearch.com/downloads
x-tagGroups: null
servers:
  - url: https://api.biblesupersearch.com
    description: Bible SuperSearch API
paths:
  /api:
    $ref: paths/api.yaml
  /api/statics:
    $ref: paths/api_statics.yaml
